apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app
  namespace: default
spec:
  storageClassName: jingood2-dev-efs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi